const text = [
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ante arcu, scelerisque id arcu sit amet, lacinia rhoncus ligula. Sed risus neque, varius vitae nisl eu, tincidunt auctor nibh. Proin efficitur felis a venenatis placerat. Phasellus vitae turpis mattis, semper mi sed, porta ipsum. Etiam convallis nibh et enim cursus viverra. Proin sed ante ut ante interdum efficitur ut at ligula. Vestibulum imperdiet vel est nec eleifend. Ut volutpat augue sit amet nunc sollicitudin, sed egestas purus bibendum. Nulla ultricies eu leo eget ultricies. Donec et vehicula dolor, vitae pharetra mauris. Vestibulum placerat pulvinar erat ut viverra. Integer lacinia sodales risus sit amet vestibulum.`,
    `Sed a sem mattis, condimentum ipsum ut, tempor libero. Maecenas volutpat justo sit amet sapien laoreet ultricies. Vivamus mattis a dui in lacinia. Donec non iaculis purus, ut posuere massa. Maecenas porta quis dui in posuere. Sed gravida tincidunt tincidunt. Aliquam placerat, leo eu interdum porta, massa eros accumsan est, sit amet elementum est mi vel justo. Donec varius tincidunt urna nec pulvinar. Praesent vitae arcu a metus hendrerit commodo. Ut viverra orci lectus, eget commodo velit gravida at. Fusce rhoncus diam eu quam porta, id consequat metus finibus. Mauris vehicula risus a tortor euismod, eget rutrum erat auctor. Praesent quis odio egestas, rutrum velit eu, rhoncus ipsum.`,
    `Ut ultrices, ligula non pharetra efficitur, sem magna porttitor mi, ultrices laoreet urna arcu et nunc. Aenean malesuada pellentesque orci, id elementum sapien bibendum ut. Mauris porta leo non nisl viverra, quis ornare libero fermentum. Phasellus ut ligula tincidunt, eleifend augue convallis, porttitor leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent venenatis bibendum nisi vel auctor. Donec laoreet ex ligula, sed tincidunt diam malesuada non. Nullam ac fermentum nisl. Duis elementum pharetra ante eu vulputate. Pellentesque vehicula posuere orci a scelerisque. Vestibulum vehicula turpis quam, a ullamcorper sapien aliquet sed. Fusce placerat efficitur velit ac iaculis.`,
    `Sed convallis risus et gravida tincidunt. Duis pellentesque at ipsum scelerisque facilisis. Vestibulum lacinia elit et orci consectetur venenatis. Cras pretium nulla semper ultrices venenatis. Aliquam at elit ac erat feugiat scelerisque eu id sem. Pellentesque a leo vestibulum, pulvinar nibh vel, faucibus sem. Nulla euismod ex sed dignissim bibendum. Suspendisse eget diam molestie, mollis urna quis, mollis tortor. Vivamus dui libero, aliquet in lacus quis, dictum aliquam tortor. Phasellus eu sapien sit amet metus eleifend lobortis eu id velit. Quisque facilisis purus eros, in iaculis sem fringilla sed. Ut malesuada nisl eu viverra efficitur. Nunc venenatis pulvinar tortor eu convallis.`,
    `Phasellus eget magna nec enim vestibulum egestas. Ut iaculis libero ac justo ornare pretium. Suspendisse a sollicitudin augue. Vivamus arcu nisi, vestibulum pellentesque leo at, dictum laoreet purus. Praesent nisi dolor, tempus quis lacinia ac, blandit sit amet sapien. Nulla diam dui, porta sit amet suscipit id, eleifend nec sem. Etiam porttitor arcu ex, a pretium enim semper varius. Aenean sollicitudin pellentesque magna, non ultricies urna consequat quis. Sed lobortis, sapien et tempus finibus, nisl sapien pharetra erat, id sollicitudin massa nunc eget sem. Aliquam ac purus vel augue sodales bibendum. Quisque auctor arcu libero, a varius ligula commodo nec. Fusce eu nibh eget risus dictum pellentesque. Cras sodales hendrerit eleifend. Aenean placerat eros non tincidunt laoreet. Cras venenatis congue augue laoreet tempus. Duis eget tellus eu velit dictum rhoncus vel luctus ligula.`,
    `Fusce posuere malesuada dui, vitae tristique diam suscipit vel. Phasellus pulvinar imperdiet vehicula. Vestibulum vehicula, lorem at congue rutrum, dolor velit blandit enim, vitae ultricies ante justo ut turpis. Nunc tortor enim, pretium quis nibh sit amet, congue malesuada dui. Vivamus nulla diam, rhoncus a mauris quis, tempor fringilla erat. Suspendisse in tincidunt lectus, vitae facilisis metus. Vivamus eget accumsan enim, ac blandit nisl. Nunc ex nibh, elementum vel interdum eget, tempus sed sapien. In lacus tortor, iaculis tempor felis eget, aliquam egestas ipsum. Sed nunc nibh, faucibus mattis ante eu, auctor aliquet nibh. Nulla vestibulum molestie nulla nec mollis. Quisque et pretium diam. Integer a convallis massa, id sollicitudin sem. Donec ullamcorper ullamcorper iaculis.`,
    `Praesent finibus ultrices lectus ut euismod. Integer at condimentum velit, eget hendrerit odio. Curabitur id lectus justo. Praesent accumsan pretium dolor vel tempor. In nibh ex, aliquet quis sem vitae, elementum vehicula ipsum. Aliquam semper neque malesuada diam vulputate, vel mattis velit interdum. Etiam velit elit, sollicitudin nec consectetur in, vestibulum id diam. Praesent viverra mi diam, vel scelerisque nunc consequat nec. Donec sagittis laoreet risus, id finibus turpis molestie sed. Ut sagittis euismod diam, in dignissim nulla varius quis. Donec felis massa, sollicitudin eget neque id, rhoncus pretium massa. Duis quis imperdiet leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla pellentesque purus elit, nec porta justo facilisis eu.`,
    `nteger ex mauris, fringilla eu convallis a, molestie eu elit. Quisque id velit dolor. Praesent convallis massa vitae elementum malesuada. Donec sit amet elementum arcu, eu ultrices tortor. Vivamus non ante vulputate, bibendum quam a, sollicitudin velit. Ut fringilla elementum odio, vel porttitor mi ultricies nec. Curabitur id sapien metus. Phasellus quam odio, scelerisque nec nunc nec, molestie porttitor nisi. Nunc tellus velit, placerat nec ipsum ac, faucibus vulputate justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta varius est non consequat. Praesent fermentum lorem eu nisl pharetra euismod. Praesent dapibus, eros at venenatis dignissim, dolor massa lobortis velit, eu vehicula dui nunc pellentesque metus. Donec interdum est lorem, quis pulvinar felis egestas nec. Donec et nibh commodo, vehicula augue quis, tristique massa. Sed tristique, ante quis placerat lobortis, lectus ligula fringilla purus, id finibus sem sapien sed purus.`,
    `When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then`,
    `The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen.`,
    `When, while teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath
`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`,
    `when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath of that universal love which bears and sustains us, as it floats around us in an eternity of bliss; and then, my friend, when darkness overspreads my eyes, and heaven and earth seem to dwell in my soul and absorb its power, like the form of a beloved mistress, then I often think with longing, Oh, would I could describe these conceptions, could impress upon paper all that is living so full and warm within me, that it might be the mirror of my soul, as my soul is the mirror of the infinite God!`
];
// select element
const amount = document.getElementById('amount')
const form = document.querySelector('.lorem-form');
const result = document.querySelector('.lorem-text');
const error = document.querySelector('#error');



form.addEventListener('submit', function (e) {
    e.preventDefault();
    const value = parseInt(amount.value);
    const randomvalue = Math.floor(Math.random() * text.length);
   



    if (value >= 24) {

        error.innerHTML = `${amount.value} Pragraph are not available only   ${text.length} paragraph are available `;

    }
    else if ((isNaN(value) || value <= 0)) {

        error.innerHTML = ` Please enter the number of pragraph you want to generate`;

    } else {
        let temptext = text.slice(0, value);
        console.log(temptext);
        error.innerHTML = ``;
        document.getElementById("succsess").innerHTML = "generated SuccessFully";
       
        
        

//    notify when text generated
        setTimeout(function () {
            document.getElementById("succsess").innerHTML = "";
        }, 800);

        temptext = temptext.map((item) => {
            return `<p class=result">${item} </p>`;
        })
            .join("")
        result.innerHTML = temptext;
    }

});